/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Casio;

/**
 *
 * @author Admin
 */
public class CasioBasicJFrame extends javax.swing.JFrame {

    private double currentValue = 0;  // Giá trị hiện tại
    private double previousValue = 0; // Giá trị trước đó
    private String phepToan = "";    // Phép toán đang thực hiện

    public CasioBasicJFrame() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelKetQua = new javax.swing.JPanel();
        jLabelKetQua = new javax.swing.JLabel();
        jPanelChucNang = new javax.swing.JPanel();
        jButtonSo1 = new javax.swing.JButton();
        jButtonSo2 = new javax.swing.JButton();
        jButtonSo3 = new javax.swing.JButton();
        jButtonPhepChia = new javax.swing.JButton();
        jButtonBinhPhuong = new javax.swing.JButton();
        jButtonSo4 = new javax.swing.JButton();
        jButtonSo5 = new javax.swing.JButton();
        jButtonSo6 = new javax.swing.JButton();
        jButtonPhepNhan = new javax.swing.JButton();
        jButtonPhanTram = new javax.swing.JButton();
        jButtonSo7 = new javax.swing.JButton();
        jButtonSo8 = new javax.swing.JButton();
        jButtonSo9 = new javax.swing.JButton();
        jButtonPhepTru = new javax.swing.JButton();
        jButtonMotPhan = new javax.swing.JButton();
        jButtonSo0 = new javax.swing.JButton();
        jButtonAmDuong = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonPhepCong = new javax.swing.JButton();
        jButtonDauBang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelKetQua.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabelKetQua.setText("0");

        javax.swing.GroupLayout jPanelKetQuaLayout = new javax.swing.GroupLayout(jPanelKetQua);
        jPanelKetQua.setLayout(jPanelKetQuaLayout);
        jPanelKetQuaLayout.setHorizontalGroup(
            jPanelKetQuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelKetQua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelKetQuaLayout.setVerticalGroup(
            jPanelKetQuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKetQuaLayout.createSequentialGroup()
                .addComponent(jLabelKetQua, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelChucNang.setLayout(new java.awt.GridLayout(4, 5));

        jButtonSo1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo1.setText("1");
        jButtonSo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo1ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo1);

        jButtonSo2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo2.setText("2");
        jButtonSo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo2ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo2);

        jButtonSo3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo3.setText("3");
        jButtonSo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo3ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo3);

        jButtonPhepChia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPhepChia.setText("/");
        jButtonPhepChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhepChiaActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonPhepChia);

        jButtonBinhPhuong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonBinhPhuong.setText("Sqrt");
        jButtonBinhPhuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBinhPhuongActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonBinhPhuong);

        jButtonSo4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo4.setText("4");
        jButtonSo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo4ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo4);

        jButtonSo5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo5.setText("5");
        jButtonSo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo5ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo5);

        jButtonSo6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo6.setText("6");
        jButtonSo6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo6ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo6);

        jButtonPhepNhan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPhepNhan.setText("*");
        jButtonPhepNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhepNhanActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonPhepNhan);

        jButtonPhanTram.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPhanTram.setText("%");
        jButtonPhanTram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhanTramActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonPhanTram);

        jButtonSo7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo7.setText("7");
        jButtonSo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo7ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo7);

        jButtonSo8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo8.setText("8");
        jButtonSo8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo8ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo8);

        jButtonSo9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo9.setText("9");
        jButtonSo9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo9ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo9);

        jButtonPhepTru.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPhepTru.setText("-");
        jButtonPhepTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhepTruActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonPhepTru);

        jButtonMotPhan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMotPhan.setText("1/X");
        jButtonMotPhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMotPhanActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonMotPhan);

        jButtonSo0.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonSo0.setText("0");
        jButtonSo0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSo0ActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonSo0);

        jButtonAmDuong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonAmDuong.setText("+/-");
        jButtonAmDuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAmDuongActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonAmDuong);

        jButtonC.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonC.setText("C");
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonC);

        jButtonPhepCong.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonPhepCong.setText("+");
        jButtonPhepCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhepCongActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonPhepCong);

        jButtonDauBang.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonDauBang.setText("=");
        jButtonDauBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDauBangActionPerformed(evt);
            }
        });
        jPanelChucNang.add(jButtonDauBang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelKetQua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelChucNang, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo2ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("2");
        } else {
            jLabelKetQua.setText(currentText + "2");
        }
    }//GEN-LAST:event_jButtonSo2ActionPerformed

    private void jButtonSo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo5ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("5");
        } else {
            jLabelKetQua.setText(currentText + "5");
        }
    }//GEN-LAST:event_jButtonSo5ActionPerformed

    private void jButtonSo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo1ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("1");
        } else {
            jLabelKetQua.setText(currentText + "1");
        }
    }//GEN-LAST:event_jButtonSo1ActionPerformed

    private void jButtonPhepChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhepChiaActionPerformed
        // TODO add your handling code here:
        previousValue = Double.parseDouble(jLabelKetQua.getText());
        phepToan = "/";
        jLabelKetQua.setText("0");
    }//GEN-LAST:event_jButtonPhepChiaActionPerformed

    private void jButtonSo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo3ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("3");
        } else {
            jLabelKetQua.setText(currentText + "3");
        }
    }//GEN-LAST:event_jButtonSo3ActionPerformed

    private void jButtonBinhPhuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBinhPhuongActionPerformed
        // TODO add your handling code here:
          double currentValue = Double.parseDouble(jLabelKetQua.getText());
        if (currentValue >= 0) {
            double result = Math.sqrt(currentValue);
            jLabelKetQua.setText(String.valueOf(result));
        } else {
            jLabelKetQua.setText("Error");
    }

    }//GEN-LAST:event_jButtonBinhPhuongActionPerformed

    private void jButtonSo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo4ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("4");
        } else {
            jLabelKetQua.setText(currentText + "4");
        }
    }//GEN-LAST:event_jButtonSo4ActionPerformed

    private void jButtonSo6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo6ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("6");
        } else {
            jLabelKetQua.setText(currentText + "6");
        }
    }//GEN-LAST:event_jButtonSo6ActionPerformed

    private void jButtonPhepNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhepNhanActionPerformed
        // TODO add your handling code here:
        previousValue = Double.parseDouble(jLabelKetQua.getText());
        phepToan = "*";
        jLabelKetQua.setText("0");
    }//GEN-LAST:event_jButtonPhepNhanActionPerformed

    private void jButtonPhanTramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhanTramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPhanTramActionPerformed

    private void jButtonSo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo7ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("7");
        } else {
            jLabelKetQua.setText(currentText + "7");
        }
    }//GEN-LAST:event_jButtonSo7ActionPerformed

    private void jButtonSo8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo8ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("8");
        } else {
            jLabelKetQua.setText(currentText + "8");
        }
    }//GEN-LAST:event_jButtonSo8ActionPerformed

    private void jButtonSo9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo9ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("9");
        } else {
            jLabelKetQua.setText(currentText + "9");
        }
    }//GEN-LAST:event_jButtonSo9ActionPerformed

    private void jButtonPhepTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhepTruActionPerformed
        // TODO add your handling code here:
        previousValue = Double.parseDouble(jLabelKetQua.getText());
        phepToan = "-";
        jLabelKetQua.setText("0");
    }//GEN-LAST:event_jButtonPhepTruActionPerformed

    private void jButtonMotPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMotPhanActionPerformed
        // TODO add your handling code here:
        double currentValue = Double.parseDouble(jLabelKetQua.getText());
    if (currentValue != 0) {
        double result = 1 / currentValue;
        jLabelKetQua.setText(String.valueOf(result));
    } else {
        jLabelKetQua.setText("Error");
    }
    }//GEN-LAST:event_jButtonMotPhanActionPerformed

    private void jButtonSo0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSo0ActionPerformed
        // TODO add your handling code here:
        String currentText = jLabelKetQua.getText();
        if (currentText.equals("0")) {
            jLabelKetQua.setText("0");
        } else {
            jLabelKetQua.setText(currentText + "0");
        }
    }//GEN-LAST:event_jButtonSo0ActionPerformed

    private void jButtonAmDuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAmDuongActionPerformed
        // TODO add your handling code here:
        double currentValue = Double.parseDouble(jLabelKetQua.getText());
        currentValue = -currentValue;
        jLabelKetQua.setText(String.valueOf(currentValue));
        
        
    }//GEN-LAST:event_jButtonAmDuongActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        // TODO add your handling code here:
        jLabelKetQua.setText("0");
        previousValue = 0;
        phepToan = "";
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonPhepCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhepCongActionPerformed
        // TODO add your handling code here:
        previousValue = Double.parseDouble(jLabelKetQua.getText());
        phepToan = "+";
        jLabelKetQua.setText("0");
    }//GEN-LAST:event_jButtonPhepCongActionPerformed

    private void jButtonDauBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDauBangActionPerformed
        // TODO add your handling code here:
        double currentValue = Double.parseDouble(jLabelKetQua.getText());
        double result = 0;

        switch (phepToan) {
            case "+":
                result = previousValue + currentValue;
                break;
            case "-":
                result = previousValue - currentValue;
                break;
            case "*":
                result = previousValue * currentValue;
                break;
            case "/":
                if (currentValue != 0) {
                    result = previousValue / currentValue;
                } else {
                    jLabelKetQua.setText("Error");
                    return;
                }
                break;
           
        }

        jLabelKetQua.setText(String.valueOf(result));

    }//GEN-LAST:event_jButtonDauBangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CasioBasicJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAmDuong;
    private javax.swing.JButton jButtonBinhPhuong;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonDauBang;
    private javax.swing.JButton jButtonMotPhan;
    private javax.swing.JButton jButtonPhanTram;
    private javax.swing.JButton jButtonPhepChia;
    private javax.swing.JButton jButtonPhepCong;
    private javax.swing.JButton jButtonPhepNhan;
    private javax.swing.JButton jButtonPhepTru;
    private javax.swing.JButton jButtonSo0;
    private javax.swing.JButton jButtonSo1;
    private javax.swing.JButton jButtonSo2;
    private javax.swing.JButton jButtonSo3;
    private javax.swing.JButton jButtonSo4;
    private javax.swing.JButton jButtonSo5;
    private javax.swing.JButton jButtonSo6;
    private javax.swing.JButton jButtonSo7;
    private javax.swing.JButton jButtonSo8;
    private javax.swing.JButton jButtonSo9;
    private javax.swing.JLabel jLabelKetQua;
    private javax.swing.JPanel jPanelChucNang;
    private javax.swing.JPanel jPanelKetQua;
    // End of variables declaration//GEN-END:variables
}
